### ISSUE TITLE
Requiring Chef 12.7+ is a major breaking change

### ISSUE THREAD

**Issue by dgreene-r7** [chef-cookbooks/ark#193]
### Cookbook version
v3.1.0

### Chef-client version
12.5

### Scenario:
Use the cookbook
 
 
Introducing breaking changes by changing the Chef requirements should be a major version release.

Please note the guidelines for semantic versioning:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

The right, but complicated, thing to do would be to remove the 3.1.0 release and re-release as 4.0.0. The reality is you probably won't do that so please be more careful about introducing breaking changes in anything other than a major release.

Thanks!

**Comment by iennae** [comment]
We have had a number of complaints about overuse of major releases for "not big enough" for a major release. This influenced our decision to release this as a minor release. 

Please be aware that as part of the [Chef RFC process](https://github.com/chef/chef-rfc/blob/0d9b6edf6cc0350e8f4de861e5db4d1427eba6a5/rfc081-release-cadence.md), it has been determined that Chef-managed community cookbooks should support at least the latest 6 months of Chef Client versions. After 6 months, Chef-managed community cookbooks may elect to drop support for older Chef Client. That 6 month version is **12.16.42**. Due to some changes in Chef 12.18, we needed to remove ".class_eval" use in custom resources. Depending on how folks perceived the RFC for cookbook support this could mean that removing cookbook support for older versions of Chef is not a "major change" requiring a major release. 

That said, we appreciate you reporting this issue. We've talked about this internally, and have decided that we're going to go ahead and make this specific change a major change going forward for other cookbooks. We may have broken expectations for folks in the process of this release, but removing the release may break other folks. We will not be removing the 3.1.0 release of this cookbook.

**Comment by dgreene-r7** [comment]
Thanks!!
